<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <RootNamespace>Videoficha</RootNamespace>
        <ApplicationIcon>Assets\Images\icon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2895-prerelease" />
      <PackageReference Include="Microsoft.Windows.Compatibility" Version="9.0.0-rc.2.24474.4" />
      <PackageReference Include="System.Management" Version="9.0.0-rc.2.24473.5" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\Fonts\FormaDJRDisplay-Regular.ttf" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Assets\Samples\sample.pdf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\Fonts\FormaDJRMicro-Bold.ttf" />
      <Resource Include="Assets\Fonts\FormaDJRMicro-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <None Remove="Assets\Fonts\FormaDJRMicro-Regular.ttf" />
      <Resource Include="Assets\Fonts\FormaDJRMicro-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <None Remove="Assets\Samples\HP.wmv" />
      <Content Include="Assets\Samples\HP.wmv">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\Samples\sample.pdf" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Assets\Images\icon.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets\Images\*.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>


</Project>
